### ISSUE TITLE
New Node not starting from block 0

### ISSUE THREAD

**Issue by sankararaok** [helium/blockchain-node#123]
I have started a new node , by building the code and publishing as a docker as below.
sudo docker run -d --init --publish 44158:44158/tcp --publish 4467:4467/tcp --name node --mount type=bind,source=/disk/helium/data,target=/var/data  helium/node:latest.
But  it started synching blocks from the time i started node, discarding old blocks.
Help me here if i missed any params for full archive node.

**Comment by 1921Aaron** [comment]
I think you can just put honor_quick_sync to false in sys.config to just start syncing from 1.

**Comment by madninja** [comment]
Syncing a node from genesis requires you to turn of `{honor_quick_sync, true}` . It will take a very long time to sync from genesis given how few nodes have a full chain history on the network. 

blockchain-node was designed (like hotspots and validators) to quick sync from a recent snapshot
