### ISSUE TITLE
Testnet blockchain-node

### ISSUE THREAD

**Issue by fmira21** [helium/blockchain-node#166]
Hi guys!
Previously, I built both Testnet and Mainnet nodes by myself. After the latest update, I would like to use the opportunity to utilise your pre-built images from https://quay.io/repository/team-helium/blockchain-node. 

But I cannot see the Testnet node images for last versions there. Where can I find them? Do you build these images?

**Comment by madninja** [comment]
We have not tagged a testnet docker image in quite some time. Most testnet runs are done with source/deb builds
