### ISSUE TITLE
How to speed up node syncing?

### ISSUE THREAD

**Issue by fmira21** [helium/blockchain-node#185]
Hi guys!

After the latest update, I had to resync my node from the latest snapshot. It became 150k blocks behind the blockchain height. Now it's syncing, but the process is insanely slow: about 1000 blocks for 5 hours.
Is there a way to speed up syncing or provide a closer snapshot?

I use the official blockchain-node Docker image from quai.io

Thank you in advance!

**Comment by bsgrigorov** [comment]
I have the same issue. I tried using a snapshot I generated from the miner, but it fails with errors. When starting the node I see it starts from an old snapshot and it will take days before it resyncs: 
```@blockchain_worker:start_snapshot_sync:{1150,43} Loading snap from "/var/data/snap/snap-1431361.gz"```
