### ISSUE TITLE
Stake and unstake via RPC

### ISSUE THREAD

**Issue by varshard** [helium/blockchain-node#44]
The RPC doesn't support staking and unstaking yet.

**Comment by abhay** [comment]
Staking transactions can be submitted via the [transaction submission endpoint](https://github.com/helium/blockchain-node/blob/master/docs/blockchain_node-reference.md#pending_transaction_submit). A list of supported transactions are [here](https://github.com/helium/blockchain-node/blob/master/src/bn_pending_txns.erl#L9-L26).
