### ISSUE TITLE
Which is the JSON API port?

### ISSUE THREAD

**Issue by terrancewong** [helium/blockchain-node#46]
no documents mentioned

**Comment by lthiery** [comment]
It’s on the README page

https://helium.github.io/blockchain-node/blockchain_node-reference.html

**Comment by terrancewong** [comment]
There is NO listening port information in it.

**Comment by madninja** [comment]
> There is NO listening port information in it.

The port is defined here: https://github.com/helium/blockchain-node/blob/master/config/sys.config#L5
