### ISSUE TITLE
How to run a "full node"?

### ISSUE THREAD

**Issue by terrancewong** [helium/blockchain-node#48]
by default node is using `quick_sync_mode, blessed_snapshot` from `blessed_snapshot_block_height, 983521`.

Questions:
1. how to set up a full node?
2. is it possible to change `blessed_snapshot_block_height` ?

**Comment by madninja** [comment]
> by default node is using `quick_sync_mode, blessed_snapshot` from `blessed_snapshot_block_height, 983521`.
> 
> Questions:
> 
> 1. how to set up a full node?

What do you mean by a full node.. blockchain-node is a blockchain _follower_ that follows the chain from the configured snapshot height. 

> 2. is it possible to change `blessed_snapshot_block_height` ?

Yes.. you will have to configure blessed snapshot _hash_ and _height_ to one that was agreed to be the CG on-chain

**Comment by terrancewong** [comment]
Great!
I discovered [https://api.helium.io/v1/snapshots] has a list of **snapshots**, are **snapshots** actually **blessed snapshots** ?

And that api responses hash in base64 and shorter than 256bit, how to get erlang readable decimal array in full 256-bit?

**Comment by madninja** [comment]
> Great!
> I discovered [https://api.helium.io/v1/snapshots] has a list of **snapshots**, are **snapshots** actually **blessed snapshots** ?

They're snapshots created by the consensus group. We call them _blessed_  when they are _also_ added to the sys.config for a miner. 

> And that api responses hash in base64 and shorter than 256bit, how to get erlang readable decimal array in full 256-bit?

all base64 is base64url encoded. If you're in erlang you can run `base64url:decode("B64 content")`
