### ISSUE TITLE
Connect timeout

### ISSUE THREAD

**Issue by terrancewong** [helium/blockchain-node#52]
In console.log, tons of `connect timeout`s appear all the time

``` 
...
[warning] <0.1464.0>@libp2p_group_worker:connecting:237 Failed to connect to "/p2p/112hBQEtFkG5F7oZo7Z1T56j37Jf4YMiyn2k48VkNRknCzYgbQFi": [{"/ip4/67.211.219.199/tcp/2154",timeout}]
...
```

But, the network connection is perfectly fine

The hotspot is connected to ethernet. Interaction with SSH is perfectly smooth. Test the connection:

``` shell
# curl 67.211.219.199:2154         
curl: (1) Received HTTP/0.9 when not allowed

# telnet 67.211.219.199 2154
Connected to 67.211.219.199
/multistream/1.0.0
...
```
even connecting to a LAN node will timeout.

Please look into this!

**Comment by madninja** [comment]
I looked into this for a bit. The timeout happens further into the stream communication between two nodes and not at the initial multistream handshake. I think this has gotten better with a lot of the p2p improvements that were made. 

I'll close this for now and we can revisit if as part of other p2p improvements as they come in
