### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by terrancewong** [helium/blockchain-node#61]
- Debian testing

```
% make
./rebar3 compile
===> Verifying dependencies...
===> Fetching blockchain (from {git,"https://github.com/helium/blockchain-core.git",
                      {ref,"b4bacdaa62f12f4c109f8349d74efce4cc6c5a5d"}})
escript: exception error: undefined function erlang:get_stacktrace/0
  in function  rebar3:main/1 (/home/runner/work/rebar3/rebar3/src/rebar3.erl, line 72)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
make: *** [Makefile:17: compile] Error 127
```
function `erlang:get_stacktrace/0` is removed from OTP 24

and `https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb` is an empty deb

is compiling entire OTP 23   the only way?

**Comment by madninja** [comment]
No, install an erlang 23 version from an apt repository as specified here: https://github.com/helium/blockchain-node#installing-ubuntu-required-packages

**Comment by terrancewong** [comment]
ok, I found the problem, this [erlang-solutions_2.0_all.deb](https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb) is very out-dated. `postinst` only has code name  up to  Ubuntu 19.04 "disco" and Debian 9.0 "stretch". 

correct package is https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_23.3.4.5-1~debian~buster_amd64.deb.

or manually create a `.list` under `/etc/apt/source.list.d/ with

```
deb https://packages.erlang-solutions.com/ubuntu stretch contrib
```
only repo for "strech" has esl-erlang=1:22
...

**Comment by terrancewong** [comment]
The problem is [erlang-solutions_2.0_all.deb](https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb) is very out-dated. only has code names for Ubuntu up to 19.04 "disco" and Debian up to 9 "stretch". 

a `.list` must be manually created under `/etc/apt/sources.list.d/`
```
deb https://packages.erlang-solutions.com/ubuntu stretch contrib
```
or 
```
deb https://packages.erlang-solutions.com/ubuntu focal contrib
```
for 3 years old **new** OSes.

**Comment by madninja** [comment]
you are right.. the esl source list is apparently quite out of date. Would you be willing to update the README to reflect installation instructions as needed for newer versions of Debian/Ubuntu?

**Comment by terrancewong** [comment]
and, OTP 22 has some unmet deps with Debian `testing`. and OTP 23 works fine in ubuntu 21.04

**Comment by madninja** [comment]
I believe blockchain-node should work fine with OTP 23

**Comment by terrancewong** [comment]
OTP 24 just has a deprecated `erlang:get_stacktrace/0`, how about make it work :-D

**Comment by madninja** [comment]
> OTP 24 just has a deprecated `erlang:get_stacktrace/0`, how about make it work :-D

at some point yes.. just using OTP 24 will fail in a number of places across core and node.  And yes we know :-)

In the meantime you can use OTP 23
