### ISSUE TITLE
Can't fetch dependency blockchain-core

### ISSUE THREAD

**Issue by dominicletz** [helium/blockchain-node#64]
Just trying to build it seems you missed to make all dependencies public:

```
$ mix deps.get
* Getting blockchain (git@github.com:helium/blockchain-core.git)
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by madninja** [comment]
This repo is an old umbrella for trying out some of the currently private repos. It's out of date. I'm going to archive it now. 

We'll be opening up the actual blockchain and hotspot software repos soon. Hang in there
