### ISSUE TITLE
An error is reported during synchronization

### ISSUE THREAD

**Issue by Ledagg** [helium/blockchain-node#78]
[error] <0.1687.0>@blockchain_worker:start_snapshot_sync:1041 snapshot download or loading failed because {error,no_snap_source_base_url}: [{blockchain_worker,'-start_snapshot_sync/4-fun-0-',6,[{file,"/root/blockchain-node/_build/default/lib/blockchain/src/blockchain_worker.erl"},{line,1013}]}]

**Comment by Ledagg** [comment]
How to solve this error？

**Comment by madninja** [comment]
Are you running from source or using docker ?

**Comment by syuan100** [comment]
Source probably. I actually just made a PR for this: https://github.com/helium/blockchain-node/pull/79

**Comment by Ledagg** [comment]
running from source




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Marc ***@***.***&gt;; 
发送时间: 2021年11月8日(星期一) 晚上9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [helium/blockchain-node] An error is reported during synchronization (Issue #78)





 
Are you running from source or using docker ?
 
—

**Comment by Ledagg** [comment]
I compiled and ran it from source code

**Comment by syuan100** [comment]
@Ledagg fix should be in place. Can you test and verify that you're able to start node successfully?

**Comment by madninja** [comment]
This should be fixed on master now
