### ISSUE TITLE
how can i enable REST interface on a node?

### ISSUE THREAD

**Issue by ggxed** [helium/blockchain-node#99]
I would like to access my node as well as public via / v1 /

**Comment by madninja** [comment]
You can not. .blockchain-node is not the same as the full REST API that's exposed by blockchain-http running in front of a giant Postgres database filled by blockchain-etl. 

You can use the [jsonrpc API](https://helium.github.io/blockchain-node/blockchain_node-reference.html) to make jsonrpc requests to a node for block/transaction details
